version: '3.7'
services:
  evoluday-api:
    image: docker.okidoo.co/node-dev:latest
    container_name: evoluday-api
    dns: 1.1.1.1
    env_file:
      - ./.evoluday-api.env
      - ./.git.env
    command: tail -F anything
    networks:
      - evoluday-api
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./.npmrc:/home/node/.npmrc
      - ../:/home/node/app
      - ~/.ssh/:/home/node/.ssh/
    depends_on:
      evoluday-api-mongo:
        condition: service_healthy

  evoluday-api-minio:
    image: bitnami/minio:latest
    container_name: evoluday-api-minio
    volumes:
      - ../docker/minio:/data
    ports:
      - ${MINIO_EXPOSE_PORT_9000}:9000
      - ${MINIO_EXPOSE_PORT_9001}:9001
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - evoluday-api

  evoluday-api-mongo:
    image: mongo:latest
    container_name: evoluday-api-mongo
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - ./.mongo.env
    volumes:
      - ./mongo:/data/db
    networks:
      - evoluday-api
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  evoluday-api-redis:
    image: redis:latest
    container_name: evoluday-api-redis
    networks:
      - evoluday-api
    ports:
      - ${REDIS_PORT}:6379

networks:
  evoluday-api: